# Imagem de Origem
FROM node:20.16.0 AS build

# Diretrio de trabalho (onde a aplicao ficar dentro do container).
WORKDIR /var/www/

# Adicionando `/frontend/node_modules/.bin` para o $PATH
ENV PATH /frontend/node_modules/.bin:$PATH

# Copie o package.json e o package-lock.json para o diretório de trabalho
COPY ./package*.json /var/www/
# Instalando dependncias da aplicação e armazenando em cache.
RUN npm install
RUN npm install cors --save
RUN npm install -g http-server
RUN npm install react-scripts@5.0.1 -g
COPY . /var/www/
#RUN npm run build

CMD ["npm", "start"]