services:
  projeto_piripake:
    container_name: "projetoPiripake"
    build:
# Diretório onde se encontra o Dockerfile do frontend
      context: ./frontend/
      dockerfile: Dockerfile-frontend
# Nome personalizado para o container do frontend
    restart: always
    ports:
      - "80:80"
