services:
  frontend:
    container_name: "frontend"
    build:
# Diretório onde se encontra o Dockerfile do frontend
      context: ./frontend/
      dockerfile: Dockerfile-frontend
# Nome personalizado para o container do frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/
    depends_on:
      - backend
    networks:
      - webnet

  
  backend:
    container_name: "backend"
    build:
# Diretório onde se encontra o Dockerfile do backend
      context: ./backend/
      dockerfile: Dockerfile-backend
# Nome personalizado para o container do backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/var/www/
    networks:
      - webnet
    depends_on:
      - redis
      - db

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile-apache
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - redis
      - db
    networks:
      - webnet

  redis:
    image: redis:7.4.0
    networks:
      - webnet

  mongo:
    image: mongo:7.0.14
    networks:
      - webnet

networks:
    webnet:
      name: webnet
      driver: bridge
