# Usar a imagem oficial do Apache
FROM httpd:2.4

# # Habilitar módulos de proxy e proxy_http
# RUN apt-get update && apt-get install -y \
#     && a2enmod proxy \
#     && a2enmod proxy_http

# Copiar o arquivo de configuração personalizado para o Apache
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
